recreative_web_reverse_table:
    resource: "@RecreativeWebReverseTableBundle/Controller/"
    type:     annotation
    prefix:   /

recreative_web_videos:
    resource: "@RecreativeWebVideosBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults: { _controller: RecreativeWebUserBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



