recreative_web_reverse_table:
    resource: "@RecreativeWebReverseTableBundle/Controller/"
    type:     annotation
    prefix:   /

recreative_web_videos:
    resource: "@RecreativeWebVideosBundle/Controller/"
    type:     annotation
    prefix:   /


