# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\security\Core\User\User: plaintext
        #UserBundle\Entity\User: plaintext
        RecreativeWeb\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory,main]
        in_memory:      # type de provider
            memory:     # nom du provider
                users:
                    user:   {password: userpass, roles: ['ROLE_USER'] }
                    admin:  {password: adminpass, roles: ['ROLE_SUPER_ADMIN'] }
                        # identifiants des users autorisés
        main:
            entity:
                class: RecreativeWeb\UserBundle\Entity\User
                property: username

        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login: 
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_user
                #csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
        
                #remember_me: 
                #    key: "%secret%"

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
